#!/bin/bash

mkdir -p /srv/conda/etc/conda/activate.d
touch /srv/conda/etc/conda/activate.d/activate-cpu-count.sh
echo "export CPU_COUNT=1" > /srv/conda/etc/conda/activate.d/activate-cpu-count.sh

mkdir -p /srv/conda/etc/conda/deactivate.d
touch /srv/conda/etc/conda/activate.d/deactivate-cpu-count.sh
echo "unset CPU_COUNT" > /srv/conda/etc/conda/deactivate.d/deactivate-cpu-count.sh

export GIT_TAG=`git tag --points-at HEAD`
if [[ ! "$GIT_TAG" = "" ]]; then
    GIT_VERSION=`echo $GIT_TAG | tail -c +2`
    conda install fp17=$GIT_VERSION -c statiskit -c defaults --override-channels
fi