package:
    name: python-basic
    version: {{ DATETIME_DESCRIBE_VERSION }}

source:
    path: ../../..
  
build:
    number: {{ DATETIME_DESCRIBE_NUMBER }}
    script: 
        - scons py --prefix={{ PREFIX }} -j{{ CPU_COUNT }} --package=basic         [unix]
        - scons py --prefix={{ LIBRARY_PREFIX }} -j{{ CPU_COUNT }} --package=basic  [win]
                
about:
    home: http://autowig.readthedocs.io/
    license: Apache License 2.0

requirements:
    build:
        - libtoolchain
        - python-toolchain
        - python
        - libboost_python-dev
        - libpybind11-dev
        - libbasic
    run:
        - python
        - libboost_python-dev
        - libpybind11-dev
        - libbasic

test:
  commands:
    - python -c "from basic import __basic"
