package:
    name: python-basic
    version: {{ DATETIME_DESCRIBE_VERSION }}

source:
    path: ../../..
  
build:
    number: {{ DATETIME_DESCRIBE_NUMBER }}
    script: 
        - scons py --prefix={{ PREFIX }} -j{{ CPU_COUNT }} --package=basic         [unix]
        - scons py --prefix={{ LIBRARY_PREFIX }} -j{{ CPU_COUNT }} --package=basic  [win]
                
about:
    home: http://autowig.readthedocs.io/
    license: Apache License 2.0

requirements:
    build:
        - python-toolchain
        - libtoolchain
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - libbasic
        - libboost-dev
        - libboost_python
        - python
    run:
        - {{ pin_compatible('libbasic', exact=True) }}
        - {{ pin_compatible('libboost_python', exact=True) }}
        - python

test:
  commands:
    - python -c "from basic import __basic"
