package:
    name: fp17
    version: {{ DATETIME_DESCRIBE_VERSION }}

source:
    path: ../../..
  
build:
    number: {{ DATETIME_DESCRIBE_NUMBER }}
                
about:
    home: http://autowig.readthedocs.io/
    license: Apache License 2.0

requirements:
    build:
        - autowig-toolchain
    host:
        - python
        - gitpython
        - jupyter
        - ipykernel
        - matplotlib
        - devops-tools
    run:
        - {{ pin_compatible('autowig-toolchain', exact=True) }}
        - {{ pin_compatible('devops-tools', exact=True) }}
        - gitpython
        - jupyter
        - ipykernel
        - matplotlib
        - python
        
test:
  commands:
    - python -c "from fp17 import report"
