##################################################################################
#                                                                                #
# AutoWIG: Automatic Wrapper and Interface Generator                             #
#                                                                                #
# Homepage: http://autowig.readthedocs.io                                        #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL_V2.1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (2)                        #
#                                                                                #
##################################################################################

package:
    name: python-fp17
    version: "1.0.0"

source:
    path: ../../..
  
build:
    number: 0
    script: 
        - scons py --prefix={{ PREFIX }} -j{{ CPU_COUNT }} --package=fp17                        [unix]
        - scons py --prefix={{ LIBRARY_PREFIX }} -j{{ CPU_COUNT }} --arch=%ARCH% --package=fp17  [win]
                
about:
    home: http://autowig.readthedocs.io/
    license: Apache License 2.0

requirements:
    build:
        - libtoolchain
        - python-toolchain
        - python
    run:
        - python
        - python-autowig

test:
  commands:
    - python -c "from fp17 import report"
