package:
    name: fp17
    version: "1.0.0"

source:
    path: ../../..
  
build:
    number: 0
                
about:
    home: http://autowig.readthedocs.io/
    license: Apache License 2.0

requirements:
    build:
        - python
        - statiskit-dev
        - gitpython
        - jupyter
        - ipykernel
        - matplotlib
    run:
        - python
        - {{ pin_compatible('statiskit-dev', exact=True) }}
        - gitpython
        - jupyter
        - ipykernel
        - matplotlib
        
test:
  commands:
    - python -c "from fp17 import report"
