package:
    name: fp17
    version: "1.0.0"

source:
    path: ../../..
  
build:
    number: 0
    script: 
        - scons py --prefix={{ PREFIX }} -j{{ CPU_COUNT }} --package=fp17                        [unix]
        - scons py --prefix={{ LIBRARY_PREFIX }} -j{{ CPU_COUNT }} --arch=%ARCH% --package=fp17  [win]
                
about:
    home: http://autowig.readthedocs.io/
    license: Apache License 2.0

requirements:
    build:
        - libtoolchain
        - python-toolchain
        - python
        - python-autowig
        - python-clanglite
        - libboost_python-dev
        - gitpython
        - jupyter
        - matplotlib
    run:
        - {{ pin_compatible('libtoolchain', exact=True) }}
        - {{ pin_compatible('python-toolchain', exact=True) }}
        - python
        - {{ pin_compatible('python-autowig', exact=True) }}
        - {{ pin_compatible('python-clanglite', exact=True) }}
        - {{ pin_compatible('libboost_python-dev', exact=True) }}
        - gitpython
        - jupyter
        - matplotlib
        
test:
  commands:
    - python -c "from fp17 import report"
