package:
    name: libbasic
    version: {{ DATETIME_DESCRIBE_VERSION }}

source:
    path: ../../..

build:
    number: {{ DATETIME_DESCRIBE_NUMBER }}
    script: 
        - scons cpp --prefix={{ PREFIX }} -j{{ CPU_COUNT }}         # [unix]
        - scons cpp --prefix={{ LIBRARY_PREFIX }} -j{{ CPU_COUNT }} # [win]
    
about:
    home: http://autowig.readthedocs.io/
    license: Apache License 2.0

requirements:
    build:
        - libtoolchain
